// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer 1.0.45
//     Available from https://marketplace.visualstudio.com/items?itemName=MadsKristensen.VsixSynchronizer64
// </auto-generated>
// ------------------------------------------------------------------------------
namespace VSFastBuildVSIX
{
    internal sealed partial class Vsix
    {
        public const string Id = "VSFastBuildVSIX.a7cd32ba-4468-4093-bf42-d7b7230b77df";
        public const string Name = "VSFastBuild";
        public const string Description = @"Integration of FASTBuild for Visual Studio.";
        public const string Language = "en-US";
        public const string Version = "0.1.2";
        public const string Author = "taqu29";
        public const string Tags = "Build,FASTBuild";
        public const bool IsPreview = true;
    }
}
