// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace VSFastBuildVSIX
{
    internal sealed partial class Vsix
    {
        public const string Id = "VSFastBuildVSIX.a7cd32ba-4468-4093-bf42-d7b7230b77df";
        public const string Name = "VSFastBuildVSIX";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Company";
        public const string Tags = "";
    }
}
