// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer 1.0.45
//     Available from https://marketplace.visualstudio.com/items?itemName=MadsKristensen.VsixSynchronizer64
// </auto-generated>
// ------------------------------------------------------------------------------
namespace VSFastBuildVSIX
{
    using System;

    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string VSFastBuildVSIXString = "73d9eb2b-a45e-4cf2-81ec-517c78ad7093";
        public static Guid VSFastBuildVSIX = new Guid(VSFastBuildVSIXString);

        public const string VSFastBuildImagesString = "334e00cc-d085-4475-a258-7b02c3133597";
        public static Guid VSFastBuildImages = new Guid(VSFastBuildImagesString);

        public const string guidImagesString = "bf66704f-c9c9-4236-931f-b61d861bc317";
        public static Guid guidImages = new Guid(guidImagesString);
    }

    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int VSFastBuildMenuGroup = 0x1000;
        public const int VSFastBuildMenuSolutionGroup = 0x1001;
        public const int VSFastBuildMenuProjectGroup = 0x1002;
        public const int VSFastBuildMenuCleanGroup = 0x1003;
        public const int VSFastBuildMenuToolGroup = 0x1004;
        public const int VSFastBuildMenuBFFGroup = 0x1005;
        public const int VSFastBuildMenuBFF00Group = 0x1006;
        public const int VSFastBuildMenuBFF01Group = 0x1007;
        public const int VSFastBuildMenuBFF02Group = 0x1008;
        public const int VSFastBuildMenuBFF03Group = 0x1009;
        public const int VSFastBuildMenuBFF04Group = 0x100A;
        public const int VSFastBuildMenuBFF05Group = 0x100B;
        public const int VSFastBuildMenuBFF06Group = 0x100C;
        public const int VSFastBuildMenuBFF07Group = 0x100D;
        public const int VSFastBuildMenuBFF08Group = 0x100E;
        public const int VSFastBuildMenuBFF09Group = 0x100F;
        public const int VSFastBuildMenuBFF0AGroup = 0x1010;
        public const int VSFastBuildMenuBFF0BGroup = 0x1011;
        public const int VSFastBuildMenuBFF0CGroup = 0x1012;
        public const int VSFastBuildMenuBFF0DGroup = 0x1013;
        public const int VSFastBuildMenuBFF0EGroup = 0x1014;
        public const int VSFastBuildMenuBFF0FGroup = 0x1015;
        public const int VSFastBuildMenuBFF10Group = 0x1016;
        public const int VSFastBuildMenuBFF11Group = 0x1017;
        public const int VSFastBuildMenuBFF12Group = 0x1018;
        public const int VSFastBuildMenuBFF13Group = 0x1019;
        public const int VSFastBuildMenuBFF14Group = 0x101A;
        public const int VSFastBuildMenuBFF15Group = 0x101B;
        public const int VSFastBuildMenuBFF16Group = 0x101C;
        public const int VSFastBuildMenuBFF17Group = 0x101D;
        public const int VSFastBuildMenuBFF18Group = 0x101E;
        public const int VSFastBuildMenuBFF19Group = 0x101F;
        public const int VSFastBuildMenuBFF1AGroup = 0x1020;
        public const int VSFastBuildMenuBFF1BGroup = 0x1021;
        public const int VSFastBuildMenuBFF1CGroup = 0x1022;
        public const int VSFastBuildMenuBFF1DGroup = 0x1023;
        public const int VSFastBuildMenuBFF1EGroup = 0x1024;
        public const int VSFastBuildMenuBFF1FGroup = 0x1025;
        public const int VSFastBuildMenu = 0x2000;
        public const int VSFastBuildMenuBFF00 = 0x2001;
        public const int VSFastBuildMenuBFF01 = 0x2002;
        public const int VSFastBuildMenuBFF02 = 0x2003;
        public const int VSFastBuildMenuBFF03 = 0x2004;
        public const int VSFastBuildMenuBFF04 = 0x2005;
        public const int VSFastBuildMenuBFF05 = 0x2006;
        public const int VSFastBuildMenuBFF06 = 0x2007;
        public const int VSFastBuildMenuBFF07 = 0x2008;
        public const int VSFastBuildMenuBFF08 = 0x2009;
        public const int VSFastBuildMenuBFF09 = 0x200A;
        public const int VSFastBuildMenuBFF0A = 0x200B;
        public const int VSFastBuildMenuBFF0B = 0x200C;
        public const int VSFastBuildMenuBFF0C = 0x200D;
        public const int VSFastBuildMenuBFF0D = 0x200E;
        public const int VSFastBuildMenuBFF0E = 0x200F;
        public const int VSFastBuildMenuBFF0F = 0x2010;
        public const int VSFastBuildMenuBFF10 = 0x2011;
        public const int VSFastBuildMenuBFF11 = 0x2012;
        public const int VSFastBuildMenuBFF12 = 0x2013;
        public const int VSFastBuildMenuBFF13 = 0x2014;
        public const int VSFastBuildMenuBFF14 = 0x2015;
        public const int VSFastBuildMenuBFF15 = 0x2016;
        public const int VSFastBuildMenuBFF16 = 0x2017;
        public const int VSFastBuildMenuBFF17 = 0x2018;
        public const int VSFastBuildMenuBFF18 = 0x2019;
        public const int VSFastBuildMenuBFF19 = 0x201A;
        public const int VSFastBuildMenuBFF1A = 0x201B;
        public const int VSFastBuildMenuBFF1B = 0x201C;
        public const int VSFastBuildMenuBFF1C = 0x201D;
        public const int VSFastBuildMenuBFF1D = 0x201E;
        public const int VSFastBuildMenuBFF1E = 0x201F;
        public const int VSFastBuildMenuBFF1F = 0x2020;
        public const int CommandFBuildSolution = 0x3000;
        public const int CommandFBuildGenerateSolution = 0x3001;
        public const int CommandFBuildProject = 0x3002;
        public const int CommandFBuildMonitor = 0x3003;
        public const int CommandFBuildClean = 0x3004;
        public const int CommandFBuildBFFFiles = 0x3005;
        public const int CommandFBuildBFF00 = 0x4000;
        public const int CommandFBuildBFF01 = 0x4100;
        public const int CommandFBuildBFF02 = 0x4200;
        public const int CommandFBuildBFF03 = 0x4300;
        public const int CommandFBuildBFF04 = 0x4400;
        public const int CommandFBuildBFF05 = 0x4500;
        public const int CommandFBuildBFF06 = 0x4600;
        public const int CommandFBuildBFF07 = 0x4700;
        public const int CommandFBuildBFF08 = 0x4800;
        public const int CommandFBuildBFF09 = 0x4900;
        public const int CommandFBuildBFF0A = 0x4A00;
        public const int CommandFBuildBFF0B = 0x4B00;
        public const int CommandFBuildBFF0C = 0x4C00;
        public const int CommandFBuildBFF0D = 0x4D00;
        public const int CommandFBuildBFF0E = 0x4E00;
        public const int CommandFBuildBFF0F = 0x4F00;
        public const int CommandFBuildBFF10 = 0x5000;
        public const int CommandFBuildBFF11 = 0x5100;
        public const int CommandFBuildBFF12 = 0x5200;
        public const int CommandFBuildBFF13 = 0x5300;
        public const int CommandFBuildBFF14 = 0x5400;
        public const int CommandFBuildBFF15 = 0x5500;
        public const int CommandFBuildBFF16 = 0x5600;
        public const int CommandFBuildBFF17 = 0x5700;
        public const int CommandFBuildBFF18 = 0x5800;
        public const int CommandFBuildBFF19 = 0x5900;
        public const int CommandFBuildBFF1A = 0x5A00;
        public const int CommandFBuildBFF1B = 0x5B00;
        public const int CommandFBuildBFF1C = 0x5C00;
        public const int CommandFBuildBFF1D = 0x5D00;
        public const int CommandFBuildBFF1E = 0x5E00;
        public const int CommandFBuildBFF1F = 0x5F00;
        public const int icon_menu = 0x0001;
        public const int bmpPic1 = 0x0001;
        public const int bmpPic2 = 0x0002;
        public const int bmpPicSearch = 0x0003;
        public const int bmpPicX = 0x0004;
        public const int bmpPicArrows = 0x0005;
        public const int bmpPicStrikethrough = 0x0006;
    }
}
